version: "3.8"
services:
  api_server:
    ports:
      - 8091:8091
    build:
      context: ../../
      dockerfile: ./docker/local/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - ../../src:/app/src
      - ../../dist:/app/dist
      - ../../tsconfig.json:/app/tsconfig.json
      - ../../nodemon.json:/app/nodemon.json
    command: ["yarn", "dev"]
